#!/bin/sh

plat=`uname`

if [ -z "$VERS" ]
then
  VERS="943"
fi

if [ "$plat" = "AIX" ]
then
  # flags="-q64 -qmaxmem=-1 $CCEXTRAFLAGS -D PLATFORM_AIX"
  # cc="xlc"
  flags="-Wno-pragma-pack $CCEXTRAFLAGS -D PLATFORM_AIX"
  cc="/opt/IBM/openxlC/17.1.1/bin/ibm-clang_r"
  targdir="../bin/aix"
  optim="-O3"
elif [ "$plat" = "Darwin" ]
then
  # Ought to work through the -W flags so they can be removed without compiler warnings
  flags="-m64  -Wno-pragma-pack  $CCEXTRAFLAGS -D PLATFORM_MACOS"
  cc="gcc"
  targdir="../bin/macos"
  optim="-O3"
else
  flags="-m64 $CCEXTRAFLAGS -D PLATFORM_LINUX"
  cc="gcc"
  targdir="../bin/linux"
  optim="-O3"
fi
if [ "$CCDEBUG" != "" ]
then
  if [ "$plat" = "AIX" ]
  then
    flags="$flags -g "
  else
    flags="$flags -g -fsanitize=address,leak,undefined "
  fi
else
  flags="$flags $optim"
fi

PLATFLAGS=$flags 
CC=$cc 
VERS=$VERS
export PLATFLAGS CC VERS

make -e -f Makefile.unix $*
rc=$?
if [ $rc -ne 0 ]
then
  exit $rc
fi

mkdir -p $targdir >/dev/null 2>&1 
rm -f $targdir/convH $targdir/mqsmfcsv
cp convH mqsmfcsv $targdir

