#!/bin/sh

plat=`uname`

if [ -z "$VERS" ]
then
  VERS="934"
fi

if [ "$plat" = "AIX" ]
then
  flags="-q64 -qmaxmem=-1 $CCEXTRAFLAGS -D PLATFORM_AIX"
  cc="xlc"
  targdir="../bin/aix"
  optim="-O3"
else
  flags="-m64 $CCEXTRAFLAGS -D PLATFORM_LINUX"
  cc="gcc"
  targdir="../bin/linux"
  optim="-O3"
fi
if [ "$CCDEBUG" != "" ]
then
  if [ "$plat" = "AIX" ]
  then
    flags="$flags -g "
  else
    flags="$flags -g -fsanitize=address,leak,undefined "
  fi
else
  flags="$flags $optim"
fi

export PLATFLAGS=$flags CC=$cc VERS=$VERS
make -e -f Makefile.unix $*
rc=$?
if [ $rc -ne 0 ]
then
  exit $rc
fi

rm -f $targdir/convH $targdir/mqsmfcsv
cp convH mqsmfcsv $targdir

