#!/bin/sh

plat=`uname`

if [ -z "$VERS" ]
then
  VERS="1000"
fi

case $plat in
AIX)
  flags="-Wno-pragma-pack $CCEXTRAFLAGS -D PLATFORM_AIX"
  cc="/opt/IBM/openxlC/17.1.1/bin/ibm-clang_r"
  targdir="../bin/aix"
  optim="-O3"
  ;;
Darwin)
  flags="-m64  -Wno-pragma-pack  $CCEXTRAFLAGS -D PLATFORM_MACOS -fno-common"
  cc="gcc"
  targdir="../bin/macos"
  optim="-O3"
  ;;
*)
  flags="-m64 $CCEXTRAFLAGS -D PLATFORM_LINUX"
  cc="gcc"
  targdir="../bin/linux"
  optim="-O3"
  ;;

esac

# Add platform-specific flags for DEBUG builds
if [ "$CCDEBUG" != "" ]
then
  case $plat in
  AIX)
    flags="$flags -ggdb "
    ;;
  Darwin)
    flags="$flags -g"
    ;;
  *)
    flags="$flags -g -fsanitize=address,leak,undefined "
    ;;
  esac
else
  flags="$flags $optim"
fi

PLATFLAGS=$flags
CC=$cc
VERS=$VERS
export PLATFLAGS CC VERS

make -e -f Makefile.unix $*
rc=$?
if [ $rc -ne 0 ]
then
  exit $rc
fi

if [ "$plat" = "Darwin" ]
then
  rm -rf *dSYM
fi

mkdir -p $targdir >/dev/null 2>&1
rm -f $targdir/convH $targdir/mqsmfcsv
cp convH mqsmfcsv $targdir

